fs = 48000;
audioFrameLength = 1024;
deviceReader = audioDeviceReader(...
    'Device', 'miniDSP ASIO Driver', ...
    'Driver', 'ASIO', ...
    'SampleRate', fs, ...
    'NumChannels', 8 ,...
    'OutputDataType','double',...
    'SamplesPerFrame', audioFrameLength);
fileWriter = dsp.AudioFileWriter('ch.wav','FileFormat','WAV');
disp('Speak into microphone now.');
tic;
while toc < 10
    disp(toc)
    acquiredAudio = record(deviceReader);
    step(fileWriter, acquiredAudio(:,7:8));
end